# base/auth-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pdns-auth
  namespace: dns-system
spec:
  type: ClusterIP
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    # THE FIX: Expose the Webserver/API port to internal cluster pods
    - name: api-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: pdns-authoritative
