# base/recursor-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pdns-recursor
  namespace: dns-system
spec:
  type: LoadBalancer
  # Enforces GKE to use the modern controller supporting mixed protocols
  loadBalancerClass: networking.gke.io/l4-regional-external
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: pdns-recursor
